# Generated by Django 5.2.12 on 2026-03-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holiday',
            options={'ordering': ['-date']},
        ),
    ]
